name = "ruden-transport"
type = "javascript"
account_id = "5c9aa0f9376b4452765a1656f5d8fd1"
workers_dev = false
route = ""
zone_id = ""

[env.production]
name = "ruden-transport"
account_id = "5c9aa0f9376b4452765a1656f5d8fd1"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["client/**/*.tsx", "client/**/*.ts", "client/**/*.css"]

[build.upload]
format = "service-worker"
